changelog:
  exclude:
    labels:
      - release:none
  categories:
    - title: Breaking changes
      labels:
        - release:major
    - title: Features
      labels:
        - release:minor
        - enhancement
    - title: Fixes and improvements
      labels:
        - release:patch
        - bug
        - dependencies
    - title: Other changes
      labels:
        - "*"
