{{- if eq (include "kill-me.renderHot" .) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kill-me.resourceName" . }}
  namespace: {{ include "kill-me.namespace" . }}
  labels:
    app: {{ include "kill-me.resourceName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kill-me.resourceName" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ include "kill-me.resourceName" . }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: {{ include "kill-me.resourceName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: AZURE_APP_CONFIG_ENDPOINT
              value: https://infra-appconfig.azconfig.io
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
            failureThreshold: 3
{{- end }}
