{{- if eq (include "kill-me.renderWarm" .) "true" }}
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: {{ include "kill-me.resourceName" . }}
  namespace: {{ include "kill-me.namespace" . }}
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.ingress.gatewayName }}
    namespace: {{ .Values.ingress.gatewayNamespace }}
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.hostname | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: {{ .Values.ingress.tlsSecret }}
{{- end }}
